version: '3'

volumes:
  pg_data_production:
  static_volume:

services:
  db_user:
    image: postgres:13.10
    env_file: .env
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
    volumes:
      - pg_data_production:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  backend:
    image: sxz713/taski_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
  frontend:
    image: sxz713/taski_frontend  # Качаем с Docker Hub!!!!!!!!!
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: sxz713/taski_gateway  # Качаем с Docker Hub!!
    env_file: .env
    volumes:
      - static_volume:/staticfiles/
    ports:
      - 8084:80 